const CENTRAAL_KADER = {
    THEMAS: [
        { id: 'governance-organisatie', titel: 'Governance & Organisatie' },
        { id: 'personele-beveiliging', titel: 'Personele Beveiliging' },
        { id: 'bedrijfsmiddelen', titel: 'Beheer van Bedrijfsmiddelen' },
        { id: 'toegangsbeveiliging', titel: 'Toegangsbeveiliging' },
        { id: 'fysieke-beveiliging', titel: 'Fysieke Beveiliging' },
        { id: 'communicatiebeveiliging', titel: 'Communicatiebeveiliging' },
        { id: 'operationele-beveiliging', titel: 'Operationele Beveiliging' },
        { id: 'cryptografie', titel: 'Cryptografie' },
        { id: 'systeemontwikkeling', titel: 'Systeemacquisitie, -ontwikkeling en -onderhoud' },
        { id: 'leveranciersrelaties', titel: 'Leveranciersrelaties' },
        { id: 'incidentbeheer', titel: 'Beheer van Informatiebeveiligingsincidenten' },
        { id: 'continuiteit', titel: 'Continuïteitsbeheer' },
        { id: 'naleving', titel: 'Naleving' },
        { id: 'ai-governance', titel: 'AI Governance & Verantwoord Gebruik' }
    ],

    CONTROLS: [
        // Bestaande controls (behouden zoals ze zijn)
        {
            id: '5.01.01',
            titel: 'Verantwoordelijkheden en samenhang voor informatiebeveiliging',
            themaId: 'governance-organisatie',
            description: 'De organisatie heeft een informatiebeveiligingsbeleid opgesteld en vastgesteld door de leiding van de organisatie.',
            bioOriginalText: 'De leiding van de organisatie draagt zorg voor een informatiebeveiligingsbeleid dat beschrijft wat de doelstellingen zijn voor informatiebeveiliging, de beveiliging van operationele technologie (OT) en de verantwoordelijkheden met betrekking tot de continuïteit van de taakuitvoering van de organisatie, bedrijfscontinuïteitsmanagement (BCM).',
            praktijkuitleg: 'Zorg ervoor dat er een formeel beleidsdocument bestaat dat door het bestuur is goedgekeurd. Dit document moet duidelijk maken wie waarvoor verantwoordelijk is op het gebied van informatiebeveiliging, OT-beveiliging en bedrijfscontinuïteit.',
            hoofdvraag: 'Is er een formeel informatiebeveiligingsbeleid dat door het bestuur is vastgesteld?',
            beleidsuitgangspunt: 'Informatiebeveiliging begint met duidelijke governance en verantwoordelijkheidsverdeling',
            criticality: 'high',
            customizable: true
        },
        {
            id: '5.01.02',
            titel: 'Het informatiebeveiligingsbeleid wordt minimaal jaarlijks beoordeeld',
            themaId: 'governance-organisatie',
            description: 'De beoordeling vindt plaats in aansluiting bij de bestaande bestuurs- en P&C-cycli en externe ontwikkelingen.',
            bioOriginalText: 'Het informatiebeveiligingsbeleid wordt minimaal jaarlijks en in aansluiting bij de (bestaande) bestuurs- en Planning & Control (P&C)-cycli en externe ontwikkelingen beoordeeld en zo nodig bijgesteld.',
            praktijkuitleg: 'Plan een jaarlijkse review van het informatiebeveiligingsbeleid in. Koppel dit aan de bestaande P&C-cyclus zodat het een natuurlijk onderdeel wordt van de jaarplanning.',
            hoofdvraag: 'Wordt het informatiebeveiligingsbeleid minimaal jaarlijks geëvalueerd en bijgesteld?',
            beleidsuitgangspunt: 'Beleid moet actueel blijven door regelmatige evaluatie',
            criticality: 'medium',
            customizable: true
        },
        {
            id: '5.02.01',
            titel: 'Vastlegging verantwoordelijkheden en rollen',
            themaId: 'governance-organisatie',
            description: 'De leiding heeft vastgelegd wat de verantwoordelijkheden en rollen zijn voor informatiebeveiliging.',
            bioOriginalText: 'De leiding van de organisatie legt vast wat de verantwoordelijkheden en rollen zijn voor informatiebeveiliging binnen haar organisatie, met specifieke aandacht voor het adequaat afhandelen van incidenten.',
            praktijkuitleg: 'Maak een overzicht van wie welke rol heeft in de informatiebeveiliging. Beschrijf per rol wat hun verantwoordelijkheden zijn.',
            hoofdvraag: 'Zijn de verantwoordelijkheden en rollen voor informatiebeveiliging helder vastgelegd?',
            beleidsuitgangspunt: 'Duidelijke rollen voorkomen onduidelijkheid',
            criticality: 'high',
            customizable: true
        },
        {
            id: '5.02.02',
            titel: 'Aanstelling CISO',
            themaId: 'governance-organisatie',
            description: 'Er is een CISO aangesteld die bevoegd is om onafhankelijk te adviseren aan het bestuur.',
            bioOriginalText: 'De organisatie wijst een Chief Information Security Officer (CISO) aan die bevoegd is om onafhankelijk en zelfstandig te adviseren en te rapporteren aan het bestuur.',
            praktijkuitleg: 'Wijs formeel een CISO aan met direct toegang tot het bestuur.',
            hoofdvraag: 'Is er een CISO aangesteld met voldoende mandaat?',
            beleidsuitgangspunt: 'Informatiebeveiliging heeft een aanspreekpunt nodig op bestuursniveau',
            criticality: 'high',
            customizable: true
        },

        // NIEUWE CONTROLS - Thema 5: Organisatorisch
        {
            id: '5.03.01',
            titel: 'Scheiding van taken',
            themaId: 'toegangsbeveiliging',
            categorie: 'Organisatorisch',
            description: 'Conflicterende taken en verantwoordelijkheden behoren te worden gescheiden.',
            bioOriginalText: 'Conflicterende taken en conflicterende verantwoordelijkheden behoren te worden gescheiden.',
            praktijkuitleg: 'Identificeer functies die niet door één persoon uitgevoerd mogen worden (bijv. autoriseren én uitvoeren van betalingen). Zorg dat deze taken door verschillende personen worden gedaan.',
            hoofdvraag: 'Zijn conflicterende taken en verantwoordelijkheden gescheiden?',
            beleidsuitgangspunt: 'Het risico op fraude en fouten verminderen',
            doel: 'Het risico op fraude, fouten en het omzeilen van beheersmaatregelen voor informatiebeveiliging verminderen.',
            implementatie: 'Als de beheersmaatregel van toepassing is dan moet gebruik gemaakt worden van de bijbehorende implementatieaanwijzing uit de ISO 27002.',
            criticality: 'medium',
            customizable: true
        },
        {
            id: '5.04.02',
            titel: 'Managementverantwoordelijkheden - Externe medewerkers',
            themaId: 'personele-beveiliging',
            categorie: 'Organisatorisch',
            description: 'Gedragsregels voor extern personeel en vrijwilligers zijn in het contract vastgelegd.',
            bioOriginalText: 'Het management behoort van al het personeel te eisen dat ze informatiebeveiliging toepassen overeenkomstig het vastgestelde informatiebeveiligingsbeleid.',
            praktijkuitleg: 'Neem in contracten met externe medewerkers en vrijwilligers expliciet de gedragsregels voor informatiebeveiliging op.',
            hoofdvraag: 'Zijn gedragsregels voor externe medewerkers contractueel vastgelegd?',
            beleidsuitgangspunt: 'Extern personeel moet dezelfde regels volgen als intern personeel',
            doel: 'Bewerkstelligen dat het management zijn rol bij informatiebeveiliging begrijpt.',
            criticality: 'medium',
            customizable: true
        },
        {
            id: '5.08.01',
            titel: 'Informatiebeveiliging in projectmanagement',
            themaId: 'systeemontwikkeling',
            categorie: 'Organisatorisch',
            description: 'Informatiebeveiliging behoort te worden geïntegreerd in projectmanagement.',
            bioOriginalText: 'Informatiebeveiliging behoort te worden geïntegreerd in projectmanagement.',
            praktijkuitleg: 'Bij elk nieuw project of significante wijziging moet een risicoanalyse worden uitgevoerd en moeten beveiligingseisen worden vastgesteld.',
            hoofdvraag: 'Wordt informatiebeveiliging standaard meegenomen in projecten?',
            beleidsuitgangspunt: 'Beveiliging vanaf het begin meenemen voorkomt kostbare aanpassingen achteraf',
            doel: 'Informatiebeveiligingsrisico\'s binnen projecten effectief aanpakken.',
            criticality: 'medium',
            customizable: true
        },
        {
            id: '5.09.01',
            titel: 'Inventarisatie van bedrijfsmiddelen',
            themaId: 'bedrijfsmiddelen',
            categorie: 'Organisatorisch',
            description: 'Er is een inventaris van bedrijfsmiddelen die van belang zijn voor informatieverwerking.',
            bioOriginalText: 'Er behoort een inventarislijst van informatie en andere gerelateerde bedrijfsmiddelen, met inbegrip van de eigenaren, te worden opgesteld en onderhouden.',
            praktijkuitleg: 'Maak een lijst van alle hardware, software, data en diensten. Wijs eigenaren toe en houd het actueel.',
            hoofdvraag: 'Is er een actuele inventaris van alle bedrijfsmiddelen?',
            beleidsuitgangspunt: 'Je kunt alleen beschermen wat je kent',
            doel: 'Bedrijfsmiddelen identificeren om informatiebeveiliging te behouden.',
            criticality: 'high',
            customizable: true
        },
        {
            id: '5.10.01',
            titel: 'Aanvaard gebruik van bedrijfsmiddelen',
            themaId: 'bedrijfsmiddelen',
            categorie: 'Organisatorisch',
            description: 'Regels voor aanvaardbaar gebruik van bedrijfsmiddelen zijn gedocumenteerd en geïmplementeerd.',
            bioOriginalText: 'Regels voor het aanvaardbaar gebruik van en procedures voor het omgaan met informatie en andere gerelateerde bedrijfsmiddelen behoren te worden geïdentificeerd.',
            praktijkuitleg: 'Stel regels op voor wat wel en niet mag met bedrijfsmiddelen (bijv. geen privégebruik, geen illegale software).',
            hoofdvraag: 'Zijn er regels voor acceptabel gebruik van bedrijfsmiddelen?',
            beleidsuitgangspunt: 'Duidelijke gebruiksregels beschermen bedrijfsmiddelen',
            doel: 'Waarborgen dat bedrijfsmiddelen passend worden gebruikt.',
            criticality: 'medium',
            customizable: true
        },
        {
            id: '5.11.01',
            titel: 'Retourneren van bedrijfsmiddelen',
            themaId: 'bedrijfsmiddelen',
            categorie: 'Organisatorisch',
            description: 'Personeel retourneert alle bedrijfsmiddelen bij beëindiging van dienstverband.',
            bioOriginalText: 'Personeel en andere belanghebbenden behoren alle bedrijfsmiddelen van de organisatie bij beëindiging te retourneren.',
            praktijkuitleg: 'Zorg voor een proces waarbij bij uitdiensttreding alle laptops, telefoons, toegangspassen etc. worden ingeleverd.',
            hoofdvraag: 'Worden bedrijfsmiddelen geretourneerd bij uitdiensttreding?',
            beleidsuitgangspunt: 'Bedrijfsmiddelen beschermen bij vertrek',
            doel: 'Bedrijfsmiddelen beschermen als onderdeel van beëindigingsprocedure.',
            criticality: 'medium',
            customizable: true
        },
        {
            id: '5.12.01',
            titel: 'Classificeren van informatie',
            themaId: 'bedrijfsmiddelen',
            categorie: 'Organisatorisch',
            description: 'Informatie is geclassificeerd op basis van vertrouwelijkheid, integriteit en beschikbaarheid.',
            bioOriginalText: 'Informatie behoort te worden geclassificeerd volgens de informatiebeveiligingsbehoeften van de organisatie.',
            praktijkuitleg: 'Classificeer alle informatie (bijv. Openbaar, Intern, Vertrouwelijk, Strikt Vertrouwelijk) en behandel deze dienovereenkomstig.',
            hoofdvraag: 'Is alle informatie geclassificeerd?',
            beleidsuitgangspunt: 'Classificatie bepaalt de beschermingsmaatregelen',
            doel: 'Inzicht in beschermingsbehoeften van informatie.',
            criticality: 'high',
            customizable: true
        },
        {
            id: '5.13.01',
            titel: 'Labelen van informatie',
            themaId: 'bedrijfsmiddelen',
            categorie: 'Organisatorisch',
            description: 'Procedures voor het labelen van informatie zijn geïmplementeerd.',
            bioOriginalText: 'Om informatie te labelen, behoort een passende reeks procedures te worden ontwikkeld en geïmplementeerd.',
            praktijkuitleg: 'Voeg labels toe aan documenten en emails die de classificatie aangeven (bijv. "Vertrouwelijk" in header/footer).',
            hoofdvraag: 'Wordt informatie gelabeld volgens de classificatie?',
            beleidsuitgangspunt: 'Labels maken classificatie zichtbaar',
            doel: 'Classificatie van informatie communiceren.',
            criticality: 'medium',
            customizable: true
        },
        {
            id: '5.14.01',
            titel: 'Overdracht informatie - Internet.nl',
            themaId: 'communicatiebeveiliging',
            categorie: 'Organisatorisch',
            description: 'Websites en email voldoen aan verplichte standaarden zoals gemeten door internet.nl.',
            bioOriginalText: 'Er behoren regels voor informatieoverdracht te zijn ingesteld voor alle soorten communicatiefaciliteiten.',
            praktijkuitleg: 'Test je websites en email via internet.nl en los de bevindingen op. Streef naar 100% score.',
            hoofdvraag: 'Voldoen websites en email aan internet.nl standaarden?',
            beleidsuitgangspunt: 'Veilige communicatie via internet',
            doel: 'Beveiliging van informatie-uitwisseling handhaven.',
            criticality: 'high',
            customizable: true
        },
        {
            id: '5.14.02',
            titel: 'Overdracht informatie - Certificaten',
            themaId: 'communicatiebeveiliging',
            categorie: 'Organisatorisch',
            description: 'Publiek toegankelijke websites gebruiken Organization Validated-certificaten.',
            bioOriginalText: 'Er behoren regels voor informatieoverdracht te zijn ingesteld.',
            praktijkuitleg: 'Gebruik minimaal OV-certificaten (niet DV) voor publieke websites, tenzij risicoanalyse anders aangeeft.',
            hoofdvraag: 'Worden OV-certificaten gebruikt voor publieke websites?',
            beleidsuitgangspunt: 'Certificaten waarborgen vertrouwen',
            doel: 'Beveiliging handhaven.',
            criticality: 'medium',
            customizable: true
        },
        {
            id: '5.14.03',
            titel: 'Overdracht informatie - E-handtekeningen',
            themaId: 'communicatiebeveiliging',
            categorie: 'Organisatorisch',
            description: 'Elektronische handtekeningen voldoen aan AdES Baseline Profiles.',
            bioOriginalText: 'Er behoren regels voor informatieoverdracht te zijn ingesteld.',
            praktijkuitleg: 'Gebruik voor gekwalificeerde e-handtekeningen de AdES standaard zoals voorgeschreven door Forum Standaardisatie.',
            hoofdvraag: 'Voldoen e-handtekeningen aan de AdES standaard?',
            beleidsuitgangspunt: 'Standaardisatie waarborgt interoperabiliteit',
            doel: 'Beveiliging handhaven.',
            criticality: 'low',
            customizable: true
        },
        {
            id: '5.14.04',
            titel: 'Registratie internetfacing systemen',
            themaId: 'communicatiebeveiliging',
            categorie: 'Organisatorisch',
            description: 'Van alle internetfacing systemen is een actuele registratie.',
            bioOriginalText: 'Er behoren regels voor informatieoverdracht te zijn ingesteld.',
            praktijkuitleg: 'Houd een lijst bij van alle systemen die vanaf internet bereikbaar zijn (websites, API\'s, IP-adressen).',
            hoofdvraag: 'Is er een actuele registratie van alle internetfacing systemen?',
            beleidsuitgangspunt: 'Overzicht is nodig voor beveiliging',
            doel: 'Beveiliging handhaven.',
            criticality: 'medium',
            customizable: true
        },
        {
            id: '5.14.05',
            titel: 'Registratie bij RDO',
            themaId: 'communicatiebeveiliging',
            categorie: 'Organisatorisch',
            description: 'Publieke websites zijn geregistreerd bij Register Internetdomeinen Overheid.',
            bioOriginalText: 'Er behoren regels voor informatieoverdracht te zijn ingesteld.',
            praktijkuitleg: 'Meld alle publieke overheidswebsites aan bij het RDO en actualiseer minimaal halfjaarlijks.',
            hoofdvraag: 'Zijn alle publieke websites geregistreerd bij RDO?',
            beleidsuitgangspunt: 'Transparantie over overheidswebsites',
            doel: 'Beveiliging handhaven.',
            criticality: 'low',
            customizable: true
        },
        {
            id: '5.15.01',
            titel: 'Toegangsbeveiliging - Vertrouwde zone',
            themaId: 'toegangsbeveiliging',
            categorie: 'Organisatorisch',
            description: 'Toegang tot vertrouwde zone alleen vanaf geauthentiseerde apparatuur of veilige schil.',
            bioOriginalText: 'Er behoren regels te worden vastgesteld om fysieke en logische toegang te beheersen.',
            praktijkuitleg: 'Sta alleen toegang toe tot gevoelige netwerksegmenten vanaf geautoriseerde apparaten of via VPN.',
            hoofdvraag: 'Is toegang tot vertrouwde zones beperkt tot geauthentiseerde apparatuur?',
            beleidsuitgangspunt: 'Vertrouwen moet technisch worden afgedwongen',
            doel: 'Toegang voor bevoegden bewerkstelligen.',
            criticality: 'high',
            customizable: true
        },
        {
            id: '5.18.01',
            titel: 'Toegangsrechten',
            themaId: 'toegangsbeveiliging',
            categorie: 'Organisatorisch',
            description: 'Toegangsrechten worden verstrekt, beoordeeld, aangepast en verwijderd volgens beleid.',
            bioOriginalText: 'Toegangsrechten behoren te worden verstrekt, beoordeeld, aangepast en verwijderd overeenkomstig het beleid.',
            praktijkuitleg: 'Zorg voor een formeel proces voor aanvragen, goedkeuren en intrekken van toegangsrechten.',
            hoofdvraag: 'Is er een formeel proces voor toegangsrechtenbeheer?',
            beleidsuitgangspunt: 'Gecontroleerd toegangsbeheer voorkomt onbevoegde toegang',
            doel: 'Toegang volgens bedrijfseisen vaststellen.',
            criticality: 'high',
            customizable: true
        },
        {
            id: '5.18.02',
            titel: 'Monitoring bijzondere rechten',
            themaId: 'toegangsbeveiliging',
            categorie: 'Organisatorisch',
            description: 'Het maken en aanpassen van accounts met bijzondere rechten wordt gemonitord.',
            bioOriginalText: 'Toegangsrechten behoren te worden verstrekt, beoordeeld, aangepast en verwijderd.',
            praktijkuitleg: 'Log en monitor alle wijzigingen aan admin-accounts. Behandel ongeautoriseerde wijzigingen als incident.',
            hoofdvraag: 'Worden wijzigingen aan admin-accounts gemonitord?',
            beleidsuitgangspunt: 'Extra controle op beheerdersrechten',
            doel: 'Toegang volgens bedrijfseisen vaststellen.',
            criticality: 'high',
            customizable: true
        },
        {
            id: '5.18.03',
            titel: 'Jaarlijkse review toegangsrechten',
            themaId: 'toegangsbeveiliging',
            categorie: 'Organisatorisch',
            description: 'Alle uitgegeven toegangsrechten worden minimaal jaarlijks beoordeeld.',
            bioOriginalText: 'Toegangsrechten behoren te worden verstrekt, beoordeeld, aangepast en verwijderd.',
            praktijkuitleg: 'Plan een jaarlijkse controle waarbij eigenaren bevestigen dat alle toegangsrechten nog nodig zijn.',
            hoofdvraag: 'Worden toegangsrechten jaarlijks gecontroleerd?',
            beleidsuitgangspunt: 'Reguliere controle voorkomt rechtencreep',
            doel: 'Toegang volgens bedrijfseisen vaststellen.',
            criticality: 'medium',
            customizable: true
        },
        {
            id: '5.19.01',
            titel: 'Informatiebeveiliging in leveranciersrelaties',
            themaId: 'leveranciersrelaties',
            categorie: 'Organisatorisch',
            description: 'Bij offertes zijn informatiebeveiligingseisen opgenomen gebaseerd op risicoanalyse.',
            bioOriginalText: 'Er behoren processen te worden vastgesteld om informatiebeveiligingsrisico\'s bij leveranciers te beheersen.',
            praktijkuitleg: 'Stel bij elke offerte waarin IT/informatie een rol speelt beveiligingseisen op, gebaseerd op een risicoanalyse.',
            hoofdvraag: 'Worden beveiligingseisen standaard in offertes opgenomen?',
            beleidsuitgangspunt: 'Beveiliging vanaf aanbesteding regelen',
            doel: 'Overeengekomen beveiligingsniveau handhaven.',
            criticality: 'high',
            customizable: true
        },
        {
            id: '5.20.01',
            titel: 'Beveiligingseisen in contracten',
            themaId: 'leveranciersrelaties',
            categorie: 'Organisatorisch',
            description: 'Beveiligingseisen uit offertes worden expliciet in contracten opgenomen.',
            bioOriginalText: 'Relevante informatiebeveiligingseisen behoren met elke leverancier te worden overeengekomen.',
            praktijkuitleg: 'Neem alle beveiligingseisen uit de offerte expliciet op in het definitieve contract.',
            hoofdvraag: 'Worden beveiligingseisen contractueel vastgelegd?',
            beleidsuitgangspunt: 'Contractuele vastlegging maakt eisen afdwingbaar',
            doel: 'Overeengekomen beveiligingsniveau handhaven.',
            criticality: 'high',
            customizable: true
        },
        {
            id: '5.20.02',
            titel: 'Uitsluiten algemene voorwaarden',
            themaId: 'leveranciersrelaties',
            categorie: 'Organisatorisch',
            description: 'Algemene voorwaarden leveranciers worden uitgesloten of risico\'s worden beoordeeld.',
            bioOriginalText: 'Relevante informatiebeveiligingseisen behoren met elke leverancier te worden overeengekomen.',
            praktijkuitleg: 'Sluit leveranciersvoorwaarden uit waar mogelijk. Bij acceptatie: beoordeel risico\'s expliciet.',
            hoofdvraag: 'Worden leveranciersvoorwaarden kritisch beoordeeld?',
            beleidsuitgangspunt: 'Eigen voorwaarden beschermen beter',
            doel: 'Overeengekomen beveiligingsniveau handhaven.',
            criticality: 'medium',
            customizable: true
        },
        {
            id: '5.20.03',
            titel: 'Mogelijkheid externe audit',
            themaId: 'leveranciersrelaties',
            categorie: 'Organisatorisch',
            description: 'Contracten bevatten de mogelijkheid voor externe audit of vereisen certificering.',
            bioOriginalText: 'Relevante informatiebeveiligingseisen behoren met elke leverancier te worden overeengekomen.',
            praktijkuitleg: 'Neem auditrecht op in contract. Accepteer ISO 27001 of ISAE 3402 als alternatief, mits scope past.',
            hoofdvraag: 'Is er mogelijkheid tot auditen van leveranciers?',
            beleidsuitgangspunt: 'Vertrouwen moet verifieerbaar zijn',
            doel: 'Overeengekomen beveiligingsniveau handhaven.',
            criticality: 'high',
            customizable: true
        },
        {
            id: '5.20.04',
            titel: 'Exit-strategie in contract',
            themaId: 'leveranciersrelaties',
            categorie: 'Organisatorisch',
            description: 'Contracten bevatten een expliciete uitwerking van de exit-strategie.',
            bioOriginalText: 'Relevante informatiebeveiligingseisen behoren met elke leverancier te worden overeengekomen.',
            praktijkuitleg: 'Werk in het contract uit hoe je de dienst kunt beëindigen en data kunt overhevelen.',
            hoofdvraag: 'Bevatten contracten een exit-strategie?',
            beleidsuitgangspunt: 'Voorkom vendor lock-in',
            doel: 'Overeengekomen beveiligingsniveau handhaven.',
            criticality: 'medium',
            customizable: true
        },
        {
            id: '5.20.05',
            titel: 'Periodieke herbeoordeling leverancier',
            themaId: 'leveranciersrelaties',
            categorie: 'Organisatorisch',
            description: 'Leverancier toont periodiek aan dat hij voldoet aan eisen.',
            bioOriginalText: 'Relevante informatiebeveiligingseisen behoren met elke leverancier te worden overeengekomen.',
            praktijkuitleg: 'Laat leverancier regelmatig (bijv. jaarlijks) aantonen dat hij nog steeds voldoet aan eisen.',
            hoofdvraag: 'Wordt naleving door leveranciers periodiek geverifieerd?',
            beleidsuitgangspunt: 'Continue verificatie van naleving',
            doel: 'Overeengekomen beveiligingsniveau handhaven.',
            criticality: 'medium',
            customizable: true
        },
        {
            id: '5.20.06',
            titel: 'Eigen onderzoek door organisatie',
            themaId: 'leveranciersrelaties',
            categorie: 'Organisatorisch',
            description: 'Organisatie voert risicogericht zelfstandig aanvullend onderzoek uit.',
            bioOriginalText: 'Relevante informatiebeveiligingseisen behoren met elke leverancier te worden overeengekomen.',
            praktijkuitleg: 'Voer zelf audits of assessments uit bij leveranciers, naast hun eigen rapportages.',
            hoofdvraag: 'Voert de organisatie eigen onderzoek uit bij leveranciers?',
            beleidsuitgangspunt: 'Vertrouw maar controleer',
            doel: 'Overeengekomen beveiligingsniveau handhaven.',
            criticality: 'low',
            customizable: true
        },
        {
            id: '5.20.07',
            titel: 'Transparantie over nieuwe risico\'s',
            themaId: 'leveranciersrelaties',
            categorie: 'Organisatorisch',
            description: 'Leverancier is transparant over nieuwe risico\'s, kwetsbaarheden en incidenten.',
            bioOriginalText: 'Relevante informatiebeveiligingseisen behoren met elke leverancier te worden overeengekomen.',
            praktijkuitleg: 'Leg in contract vast dat leverancier direct meldt bij kwetsbaarheden, incidenten of datalekken.',
            hoofdvraag: 'Is er afspraak over transparantie bij incidenten?',
            beleidsuitgangspunt: 'Tijdige informatie maakt tijdige actie mogelijk',
            doel: 'Overeengekomen beveiligingsniveau handhaven.',
            criticality: 'high',
            customizable: true
        },
        {
            id: '5.20.08',
            titel: 'Exit-strategie (duplicate check)',
            themaId: 'leveranciersrelaties',
            categorie: 'Organisatorisch',
            description: 'Exit-strategie is expliciet uitgewerkt in contract.',
            bioOriginalText: 'Relevante informatiebeveiligingseisen behoren met elke leverancier te worden overeengekomen.',
            praktijkuitleg: 'Zelfde als 5.20.04 - werk expliciete exit-strategie uit.',
            hoofdvraag: 'Is exit-strategie contractueel vastgelegd?',
            beleidsuitgangspunt: 'Voorkom vendor lock-in',
            doel: 'Overeengekomen beveiligingsniveau handhaven.',
            criticality: 'medium',
            customizable: true
        },
        {
            id: '5.21.01',
            titel: 'Leverancier borgt eisen bij toeleveranciers',
            themaId: 'leveranciersrelaties',
            categorie: 'Organisatorisch',
            description: 'Contract bepaalt dat leverancier verantwoordelijk is voor eisen bij toeleveranciers.',
            bioOriginalText: 'Er behoren processen te worden geïmplementeerd om informatiebeveiligingsrisico\'s in de toeleveringsketen te beheersen.',
            praktijkuitleg: 'Leg vast dat leverancier dezelfde eisen doorlegt aan zijn toeleveranciers.',
            hoofdvraag: 'Is leverancier verantwoordelijk voor toeleveringsketen?',
            beleidsuitgangspunt: 'Beveiliging geldt voor hele keten',
            doel: 'Overeengekomen beveiligingsniveau in toeleveringsketen handhaven.',
            criticality: 'medium',
            customizable: true
        },
        {
            id: '5.21.02',
            titel: 'Inzicht in toeleveranciers vooraf',
            themaId: 'leveranciersrelaties',
            categorie: 'Organisatorisch',
            description: 'Leverancier geeft vooraf inzicht in keten van toeleveranciers en risico\'s.',
            bioOriginalText: 'Er behoren processen te worden geïmplementeerd om informatiebeveiligingsrisico\'s in de toeleveringsketen te beheersen.',
            praktijkuitleg: 'Vraag leverancier vooraf om overzicht van toeleveranciers en beoordeel de risico\'s.',
            hoofdvraag: 'Is er inzicht in de toeleveringsketen?',
            beleidsuitgangspunt: 'Ken je supply chain',
            doel: 'Overeengekomen beveiligingsniveau in toeleveringsketen handhaven.',
            criticality: 'medium',
            customizable: true
        },
        {
            id: '5.21.03',
            titel: 'Doorgifte eisen aan toeleveranciers',
            themaId: 'leveranciersrelaties',
            categorie: 'Organisatorisch',
            description: 'Beveiligingseisen zijn onverminderd van toepassing op toeleveranciers.',
            bioOriginalText: 'Er behoren processen te worden geïmplementeerd om informatiebeveiligingsrisico\'s in de toeleveringsketen te beheersen.',
            praktijkuitleg: 'Borg dat alle eisen die gelden voor de hoofdleverancier ook gelden voor toeleveranciers.',
            hoofdvraag: 'Gelden beveiligingseisen voor hele keten?',
            beleidsuitgangspunt: 'Zwakste schakel bepaalt de sterkte',
            doel: 'Overeengekomen beveiligingsniveau in toeleveringsketen handhaven.',
            criticality: 'medium',
            customizable: true
        },
        {
            id: '5.21.04',
            titel: 'Melden wijzigingen toeleveranciers',
            themaId: 'leveranciersrelaties',
            categorie: 'Organisatorisch',
            description: 'Leverancier meldt wijzigingen in toeleveringsketen inclusief risico\'s.',
            bioOriginalText: 'Er behoren processen te worden geïmplementeerd om informatiebeveiligingsrisico\'s in de toeleveringsketen te beheersen.',
            praktijkuitleg: 'Zorg dat leverancier meldt als toeleveranciers wijzigen, inclusief kwetsbaarheden en incidenten.',
            hoofdvraag: 'Worden wijzigingen in toeleveringsketen gemeld?',
            beleidsuitgangspunt: 'Continue monitoring van supply chain',
            doel: 'Overeengekomen beveiligingsniveau in toeleveringsketen handhaven.',
            criticality: 'medium',
            customizable: true
        },
        {
            id: '5.22.01',
            titel: 'Jaarlijkse beoordeling leverancier',
            themaId: 'leveranciersrelaties',
            categorie: 'Organisatorisch',
            description: 'Proceseigenaar beoordeelt jaarlijks of leverancier voldoet aan IB-eisen.',
            bioOriginalText: 'De organisatie behoort informatiebeveiligingspraktijken van leveranciers regelmatig te monitoren en beoordelen.',
            praktijkuitleg: 'Plan jaarlijks een beoordeling van elke leverancier op basis van aangeleverd bewijsmateriaal.',
            hoofdvraag: 'Worden leveranciers jaarlijks beoordeeld?',
            beleidsuitgangspunt: 'Regelmatige verificatie van naleving',
            doel: 'Overeengekomen beveiligingsniveau handhaven.',
            criticality: 'medium',
            customizable: true
        },
        {
            id: '5.22.02',
            titel: 'Actuele registratie leveranciers',
            themaId: 'leveranciersrelaties',
            categorie: 'Organisatorisch',
            description: 'Er is een actuele registratie van leveranciers en afgesloten contracten.',
            bioOriginalText: 'De organisatie behoort informatiebeveiligingspraktijken van leveranciers regelmatig te monitoren en beoordelen.',
            praktijkuitleg: 'Houd een actueel overzicht bij van alle leveranciers en hun contracten.',
            hoofdvraag: 'Is er een actueel leveranciersregister?',
            beleidsuitgangspunt: 'Overzicht is basis voor beheer',
            doel: 'Overeengekomen beveiligingsniveau handhaven.',
            criticality: 'medium',
            customizable: true
        },
        {
            id: '5.24.01',
            titel: 'Meldloket voor incidenten',
            themaId: 'incidentbeheer',
            categorie: 'Organisatorisch',
            description: 'Er is een toegankelijk meldloket voor informatiebeveiligingsincidenten.',
            bioOriginalText: 'De organisatie behoort plannen op te stellen voor het beheren van informatiebeveiligingsincidenten.',
            praktijkuitleg: 'Richt een duidelijk meldpunt in (email, telefoon, webformulier) dat bekend is bij iedereen.',
            hoofdvraag: 'Is er een bekend meldpunt voor incidenten?',
            beleidsuitgangspunt: 'Snelle melding beperkt schade',
            doel: 'Snelle reactie op incidenten bewerkstelligen.',
            criticality: 'high',
            customizable: true
        },
        {
            id: '5.24.03',
            titel: 'Proceseigenaar lost incidenten op',
            themaId: 'incidentbeheer',
            categorie: 'Organisatorisch',
            description: 'Proceseigenaar is verantwoordelijk voor oplossen van beveiligingsincidenten.',
            bioOriginalText: 'De organisatie behoort processen en verantwoordelijkheden voor incidentbeheer te definiëren.',
            praktijkuitleg: 'Wijs per proces een eigenaar aan die verantwoordelijk is voor oplossen van incidenten.',
            hoofdvraag: 'Zijn verantwoordelijkheden voor incidentafhandeling helder?',
            beleidsuitgangspunt: 'Duidelijke verantwoordelijkheden bij incidenten',
            doel: 'Snelle reactie op incidenten bewerkstelligen.',
            criticality: 'high',
            customizable: true
        },
        {
            id: '5.24.04',
            titel: 'Maandelijkse rapportage incidenten',
            themaId: 'incidentbeheer',
            categorie: 'Organisatorisch',
            description: 'Opvolging van incidenten wordt maandelijks gerapporteerd aan eindverantwoordelijke.',
            bioOriginalText: 'De organisatie behoort processen en verantwoordelijkheden voor incidentbeheer te definiëren.',
            praktijkuitleg: 'Rapporteer maandelijks over status en opvolging van beveiligingsincidenten aan het management.',
            hoofdvraag: 'Wordt er maandelijks gerapporteerd over incidenten?',
            beleidsuitgangspunt: 'Management informeren voor sturing',
            doel: 'Snelle reactie op incidenten bewerkstelligen.',
            criticality: 'medium',
            customizable: true
        },
        {
            id: '5.24.06',
            titel: 'Supply chain in risicoanalyse',
            themaId: 'incidentbeheer',
            categorie: 'Organisatorisch',
            description: 'Beveiliging van toeleveringsketens is onderdeel van risicoanalyse.',
            bioOriginalText: 'De organisatie behoort processen voor incidentbeheer te definiëren.',
            praktijkuitleg: 'Neem supply chain risico\'s mee in je risicoanalyses, inclusief kwetsbaarheden bij leveranciers.',
            hoofdvraag: 'Zijn supply chain risico\'s onderdeel van risicoanalyse?',
            beleidsuitgangspunt: 'Supply chain is een significant risico',
            doel: 'Snelle reactie op incidenten bewerkstelligen.',
            criticality: 'medium',
            customizable: true
        },
        {
            id: '5.26.01',
            titel: 'Reageren op incidenten',
            themaId: 'incidentbeheer',
            categorie: 'Organisatorisch',
            description: 'Op incidenten wordt gereageerd volgens gedocumenteerde procedures.',
            bioOriginalText: 'Op informatiebeveiligingsincidenten behoort te worden gereageerd in overeenstemming met gedocumenteerde procedures.',
            praktijkuitleg: 'Documenteer hoe je reageert op verschillende soorten incidenten en train het team hierin.',
            hoofdvraag: 'Zijn er procedures voor incidentrespons?',
            beleidsuitgangspunt: 'Voorbereiding bepaalt effectiviteit van respons',
            doel: 'Effectieve reactie op incidenten bewerkstelligen.',
            criticality: 'high',
            customizable: true
        },
        {
            id: '5.27.01',
            titel: 'Leren van incidenten - Analyse',
            themaId: 'incidentbeheer',
            categorie: 'Organisatorisch',
            description: 'Beveiligingsincidenten worden geanalyseerd om achterliggende oorzaken vast te stellen.',
            bioOriginalText: 'Kennis opgedaan met incidenten behoort te worden gebruikt om beheersmaatregelen te versterken.',
            praktijkuitleg: 'Voer na elk significant incident een rootcause analyse uit en implementeer verbeteringen.',
            hoofdvraag: 'Worden incidenten geanalyseerd op rootcause?',
            beleidsuitgangspunt: 'Leren van fouten voorkomt herhaling',
            doel: 'Waarschijnlijkheid van toekomstige incidenten verminderen.',
            criticality: 'medium',
            customizable: true
        },
        {
            id: '5.27.02',
            titel: 'Leren van incidenten - Delen kennis',
            themaId: 'incidentbeheer',
            categorie: 'Organisatorisch',
            description: 'Analyses van incidenten worden breed gedeeld met relevante partners.',
            bioOriginalText: 'Kennis opgedaan met incidenten behoort te worden gebruikt om beheersmaatregelen te versterken.',
            praktijkuitleg: 'Deel lessons learned met andere afdelingen en relevante externe partners.',
            hoofdvraag: 'Wordt kennis over incidenten gedeeld?',
            beleidsuitgangspunt: 'Gedeelde kennis voorkomt herhaling elders',
            doel: 'Waarschijnlijkheid van toekomstige incidenten verminderen.',
            criticality: 'low',
            customizable: true
        },
        {
            id: '5.28.01',
            titel: 'Bewaartermijn forensisch materiaal',
            themaId: 'incidentbeheer',
            categorie: 'Organisatorisch',
            description: 'Informatie voor analyse van incidenten wordt minimaal drie jaar bewaard.',
            bioOriginalText: 'De organisatie behoort procedures vast te stellen voor het verzamelen en bewaren van bewijsmateriaal.',
            praktijkuitleg: 'Bewaar alle logs en informatie over incidenten minimaal 3 jaar voor mogelijke juridische procedures.',
            hoofdvraag: 'Wordt forensisch materiaal minimaal 3 jaar bewaard?',
            beleidsuitgangspunt: 'Bewijsmateriaal moet beschikbaar blijven',
            doel: 'Effectief beheer van bewijsmateriaal bewerkstelligen.',
            criticality: 'medium',
            customizable: true
        },
        {
            id: '5.29.01',
            titel: 'Informatiebeveiliging tijdens verstoring',
            themaId: 'continuiteit',
            categorie: 'Organisatorisch',
            description: 'Plannen voor waarborgen informatiebeveiliging tijdens verstoring zijn gemaakt.',
            bioOriginalText: 'De organisatie behoort plannen te maken voor informatiebeveiliging tijdens verstoring.',
            praktijkuitleg: 'Neem in BCP/DRP expliciet op hoe informatiebeveiliging wordt gewaarborgd tijdens calamiteiten.',
            hoofdvraag: 'Zijn beveiligingsmaatregelen onderdeel van calamiteitenplannen?',
            beleidsuitgangspunt: 'Beveiliging ook tijdens crisis handhaven',
            doel: 'Bedrijfsmiddelen tijdens verstoring beschermen.',
            criticality: 'medium',
            customizable: true
        },
        {
            id: '5.30.01',
            titel: 'Testen continuïteitsplannen',
            themaId: 'continuiteit',
            categorie: 'Organisatorisch',
            description: 'Proceseigenaar test jaarlijks continuïteitsplannen op werking en actualiteit.',
            bioOriginalText: 'ICT-gereedheid behoort te worden getest op basis van continuïteitseisen.',
            praktijkuitleg: 'Test jaarlijks of back-ups, noodprocedures en uitwijklocaties werken zoals bedoeld.',
            hoofdvraag: 'Worden continuïteitsplannen jaarlijks getest?',
            beleidsuitgangspunt: 'Een ongetest plan is geen plan',
            doel: 'Beschikbaarheid van bedrijfsmiddelen waarborgen.',
            criticality: 'high',
            customizable: true
        },
        {
            id: '5.30.02',
            titel: 'Identificatie kritieke systemen',
            themaId: 'continuiteit',
            categorie: 'Organisatorisch',
            description: 'Proceseigenaar identificeert kritieke systemen op basis van risicoanalyse.',
            bioOriginalText: 'ICT-gereedheid behoort te worden gepland op basis van continuïteitsdoelstellingen.',
            praktijkuitleg: 'Bepaal welke systemen kritiek zijn voor de bedrijfsvoering en actualiseer dit driejaarlijks.',
            hoofdvraag: 'Zijn kritieke systemen geïdentificeerd?',
            beleidsuitgangspunt: 'Prioritering op basis van criticiteit',
            doel: 'Beschikbaarheid van bedrijfsmiddelen waarborgen.',
            criticality: 'high',
            customizable: true
        },
        {
            id: '5.32.01',
            titel: 'Intellectuele eigendomsrechten',
            themaId: 'naleving',
            categorie: 'Organisatorisch',
            description: 'Procedures om intellectuele eigendomsrechten te beschermen zijn geïmplementeerd.',
            bioOriginalText: 'De organisatie behoort procedures te implementeren om intellectuele eigendomsrechten te beschermen.',
            praktijkuitleg: 'Zorg dat alleen gelicenseerde software wordt gebruikt en dat er procedures zijn voor licentiecontrole.',
            hoofdvraag: 'Zijn er procedures voor bescherming van IP-rechten?',
            beleidsuitgangspunt: 'Naleving van licentievoorwaarden',
            doel: 'Naleving van wet- en regelgeving bewerkstelligen.',
            criticality: 'low',
            customizable: true
        },
        {
            id: '5.33.01',
            titel: 'Beschermen van registraties',
            themaId: 'naleving',
            categorie: 'Organisatorisch',
            description: 'Registraties zijn beschermd en bewaartermijnen zijn vastgelegd volgens selectielijsten.',
            bioOriginalText: 'Registraties behoren te worden beschermd tegen verlies, vernietiging en onbevoegde toegang.',
            praktijkuitleg: 'Stel voor alle informatiesystemen bewaartermijnen vast conform Archiefwet en privacywetgeving.',
            hoofdvraag: 'Zijn bewaartermijnen vastgelegd en ingericht?',
            beleidsuitgangspunt: 'Wettelijke bewaartermijnen naleven',
            doel: 'Naleving van wet- en regelgeving bewerkstelligen.',
            criticality: 'medium',
            customizable: true
        },
        {
            id: '5.34.01',
            titel: 'Privacy en bescherming persoonsgegevens',
            themaId: 'naleving',
            categorie: 'Organisatorisch',
            description: 'Organisatie voldoet aan eisen voor privacy en bescherming van persoonsgegevens.',
            bioOriginalText: 'De organisatie behoort eisen met betrekking tot privacy te identificeren en eraan te voldoen.',
            praktijkuitleg: 'Implementeer AVG-vereisten: verwerkingsregister, DPIA\'s, beveiligingsmaatregelen, meldplicht datalekken.',
            hoofdvraag: 'Wordt er voldaan aan AVG-verplichtingen?',
            beleidsuitgangspunt: 'Privacybescherming is grondrecht',
            doel: 'Naleving van privacywetgeving bewerkstelligen.',
            criticality: 'high',
            customizable: true
        },
        {
            id: '5.35.01',
            titel: 'Onafhankelijke beoordeling informatiebeveiliging',
            themaId: 'naleving',
            categorie: 'Organisatorisch',
            description: 'Er is een werkend ISMS conform ISO 27001.',
            bioOriginalText: 'De aanpak van informatiebeveiliging behoort onafhankelijk te worden beoordeeld.',
            praktijkuitleg: 'Implementeer een ISMS volgens ISO 27001 met beleid, procedures, risicoanalyse en PDCA-cyclus.',
            hoofdvraag: 'Is er een werkend ISMS volgens ISO 27001?',
            beleidsuitgangspunt: 'Systematisch informatiebeveiligingsbeheer',
            doel: 'Geschikte en effectieve informatiebeveiliging waarborgen.',
            criticality: 'high',
            customizable: true
        },
        {
            id: '5.36.01',
            titel: 'Naleving van beleid en normen',
            themaId: 'naleving',
            categorie: 'Organisatorisch',
            description: 'Naleving wordt regelmatig beoordeeld en resulteert in ICV of vergelijkbaar instrument.',
            bioOriginalText: 'Naleving van informatiebeveiligingsbeleid behoort regelmatig te worden beoordeeld.',
            praktijkuitleg: 'Rapporteer in P&C-cyclus over informatiebeveiliging en geef jaarlijks een In Control Verklaring af.',
            hoofdvraag: 'Wordt er jaarlijks een ICV afgegeven?',
            beleidsuitgangspunt: 'Verantwoording over informatiebeveiliging',
            doel: 'Implementatie en uitvoering van informatiebeveiliging bewerkstelligen.',
            criticality: 'medium',
            customizable: true
        },
        {
            id: '5.37.01',
            titel: 'Gedocumenteerde bedieningsprocedures',
            themaId: 'operationele-beveiliging',
            categorie: 'Organisatorisch',
            description: 'Bedieningsprocedures zijn gedocumenteerd en beschikbaar voor personeel.',
            bioOriginalText: 'Bedieningsprocedures voor informatieverwerkende faciliteiten behoren te worden gedocumenteerd.',
            praktijkuitleg: 'Documenteer alle standaard operationele procedures en maak deze toegankelijk voor het personeel.',
            hoofdvraag: 'Zijn operationele procedures gedocumenteerd?',
            beleidsuitgangspunt: 'Documentatie waarborgt consistentie',
            doel: 'Correcte en veilige bediening waarborgen.',
            criticality: 'medium',
            customizable: true
        },

        // NIEUWE CONTROLS - Thema 6: Mensgericht
        {
            id: '6.01.01',
            titel: 'Screeningsbeleid',
            themaId: 'personele-beveiliging',
            categorie: 'Mensgericht',
            description: 'Elke organisatie heeft een vastgesteld screeningsbeleid.',
            bioOriginalText: 'De organisatie heeft een beleid voor screening van personeel voorafgaand aan aanstelling.',
            praktijkuitleg: 'Stel beleid op voor pre-employment screening, inclusief wanneer VOG vereist is.',
            hoofdvraag: 'Is er een screeningsbeleid?',
            beleidsuitgangspunt: 'Screening vermindert risico van onbetrouwbaar personeel',
            doel: 'Geschiktheid van personeel waarborgen.',
            criticality: 'medium',
            customizable: true
        },
        {
            id: '6.02.01',
            titel: 'Verantwoordelijkheden bij aanstelling',
            themaId: 'personele-beveiliging',
            categorie: 'Mensgericht',
            description: 'Medewerkers zijn bij aanstelling gewezen op informatiebeveiligingsverantwoordelijkheden.',
            bioOriginalText: 'Alle medewerkers ondertekenen een geheimhoudingsovereenkomst bij aanstelling.',
            praktijkuitleg: 'Informeer alle nieuwe medewerkers tijdens onboarding over hun beveiligingsverantwoordelijkheden.',
            hoofdvraag: 'Worden medewerkers bij aanstelling geïnformeerd?',
            beleidsuitgangspunt: 'Bewustwording begint bij aanstelling',
            doel: 'Verantwoordelijkheden duidelijk maken.',
            criticality: 'medium',
            customizable: true
        },
        {
            id: '6.03.01',
            titel: 'Bewustwording - Algemeen',
            themaId: 'personele-beveiliging',
            categorie: 'Mensgericht',
            description: 'Alle medewerkers kennen de regels en verplichtingen voor informatiebeveiliging.',
            bioOriginalText: 'Personeel behoort passende bewustwording en training in informatiebeveiliging te krijgen.',
            praktijkuitleg: 'Zorg dat iedereen de basisregels kent en zijn verantwoordelijkheden begrijpt.',
            hoofdvraag: 'Kent iedereen de beveiligingsregels?',
            beleidsuitgangspunt: 'Bewustzijn is basis voor naleving',
            doel: 'Personeel bewust maken van verantwoordelijkheden.',
            criticality: 'high',
            customizable: true
        },
        {
            id: '6.03.02',
            titel: 'Bewustwording - Training binnen 3 maanden',
            themaId: 'personele-beveiliging',
            categorie: 'Mensgericht',
            description: 'Medewerkers hebben binnen 3 maanden training I-bewustzijn gevolgd.',
            bioOriginalText: 'Personeel behoort passende bewustwording en training in informatiebeveiliging te krijgen.',
            praktijkuitleg: 'Plan voor alle nieuwe medewerkers binnen 3 maanden een verplichte awareness training.',
            hoofdvraag: 'Volgen nieuwe medewerkers binnen 3 maanden awareness training?',
            beleidsuitgangspunt: 'Vroege training maximaliseert effectiviteit',
            doel: 'Personeel bewust maken van verantwoordelijkheden.',
            criticality: 'high',
            customizable: true
        },
        {
            id: '6.03.03',
            titel: 'Bewustwording - Management stimuleert training',
            themaId: 'personele-beveiliging',
            categorie: 'Mensgericht',
            description: 'Management benadrukt en stimuleert periodieke training informatiebeveiliging.',
            bioOriginalText: 'Personeel behoort passende bewustwording en training te krijgen.',
            praktijkuitleg: 'Laat management actief het belang van beveiligingstraining benadrukken in gesprekken en overleggen.',
            hoofdvraag: 'Stimuleert management awareness training?',
            beleidsuitgangspunt: 'Tone at the top bepaalt beveiligingscultuur',
            doel: 'Personeel bewust maken van verantwoordelijkheden.',
            criticality: 'medium',
            customizable: true
        },
        {
            id: '6.04.01',
            titel: 'Disciplinaire procedure',
            themaId: 'personele-beveiliging',
            categorie: 'Mensgericht',
            description: 'Er is een formele disciplinaire procedure voor schending van beveiligingsbeleid.',
            bioOriginalText: 'Er behoort een formele disciplinaire procedure te zijn voor schending van beleid.',
            praktijkuitleg: 'Stel vast wat de gevolgen zijn bij schending van beveiligingsregels en communiceer dit.',
            hoofdvraag: 'Is er een disciplinaire procedure?',
            beleidsuitgangspunt: 'Duidelijke consequenties stimuleren naleving',
            doel: 'Gevolgen van schending duidelijk maken.',
            criticality: 'low',
            customizable: true
        },
        {
            id: '6.05.01',
            titel: 'Verantwoordelijkheden na beëindiging dienstverband',
            themaId: 'personele-beveiliging',
            categorie: 'Mensgericht',
            description: 'Verantwoordelijkheden na beëindiging zijn gedefinieerd en gecommuniceerd.',
            bioOriginalText: 'Verantwoordelijkheden die van kracht blijven na beëindiging behoren te worden gedefinieerd.',
            praktijkuitleg: 'Leg vast welke verplichtingen na uitdiensttreding blijven gelden (bijv. geheimhouding).',
            hoofdvraag: 'Zijn post-employment verplichtingen helder?',
            beleidsuitgangspunt: 'Beveiliging stopt niet bij uitdiensttreding',
            doel: 'Belangen organisatie beschermen na beëindiging.',
            criticality: 'low',
            customizable: true
        },
        {
            id: '6.06.01',
            titel: 'Vertrouwelijkheidsovereenkomsten',
            themaId: 'personele-beveiliging',
            categorie: 'Mensgericht',
            description: 'Vertrouwelijkheidsovereenkomsten worden ondertekend door personeel en externe partijen.',
            bioOriginalText: 'Vertrouwelijkheidsovereenkomsten behoren te worden geïdentificeerd, gedocumenteerd en ondertekend.',
            praktijkuitleg: 'Laat alle medewerkers en externe partijen een NDA tekenen bij aanvang van de samenwerking.',
            hoofdvraag: 'Tekenen alle medewerkers een NDA?',
            beleidsuitgangspunt: 'Juridische borging van vertrouwelijkheid',
            doel: 'Vertrouwelijkheid van informatie handhaven.',
            criticality: 'medium',
            customizable: true
        },

        // NIEUWE CONTROLS - Thema 7: Fysiek
        {
            id: '7.01.01',
            titel: 'Inrichting beveiligde zones',
            themaId: 'fysieke-beveiliging',
            categorie: 'Fysiek',
            description: 'Beveiligde zones worden ingericht conform standaarden.',
            bioOriginalText: 'Beveiligde zones worden ingericht volgens toepasselijke standaarden voor fysieke beveiliging.',
            praktijkuitleg: 'Richt beveiligde zones in met toegangscontrole, camerabewaking en fysieke barrières volgens erkende standaarden.',
            hoofdvraag: 'Zijn beveiligde zones conform standaarden ingericht?',
            beleidsuitgangspunt: 'Fysieke beveiliging vormt basis voor informatiebeveiliging',
            doel: 'Fysieke toegang beheersen.',
            criticality: 'medium',
            customizable: true
        },
        {
            id: '7.07.02',
            titel: 'Clear desk en clear screen',
            themaId: 'fysieke-beveiliging',
            categorie: 'Fysiek',
            description: 'Clear desk en clear screen regels zijn gedefinieerd en worden afgedwongen.',
            bioOriginalText: 'Er behoren clear desk regels voor documenten en clear screen regels te worden gedefinieerd.',
            praktijkuitleg: 'Stel regels op dat werkplekken opgeruimd moeten zijn en schermen vergrendeld bij afwezigheid.',
            hoofdvraag: 'Zijn er clear desk/screen regels?',
            beleidsuitgangspunt: 'Fysieke zichtbaarheid beperken',
            doel: 'Risico op onbevoegde toegang beperken.',
            criticality: 'low',
            customizable: true
        },
        {
            id: '7.08.01',
            titel: 'Plaatsen en beschermen van apparatuur',
            themaId: 'fysieke-beveiliging',
            categorie: 'Fysiek',
            description: 'Apparatuur wordt veilig geplaatst en beschermd.',
            bioOriginalText: 'Apparatuur behoort veilig te worden geplaatst en beschermd.',
            praktijkuitleg: 'Plaats servers en netwerkapparatuur in beveiligde ruimtes met beperkte toegang.',
            hoofdvraag: 'Is kritieke apparatuur fysiek beschermd?',
            beleidsuitgangspunt: 'Fysieke beveiliging van hardware',
            doel: 'Risico op fysieke dreigingen beperken.',
            criticality: 'medium',
            customizable: true
        },
        {
            id: '7.09.01',
            titel: 'Beveiligen van bedrijfsmiddelen buiten terrein',
            themaId: 'fysieke-beveiliging',
            categorie: 'Fysiek',
            description: 'Bedrijfsmiddelen buiten het terrein worden beschermd.',
            bioOriginalText: 'Bedrijfsmiddelen buiten het gebouw behoren te worden beschermd.',
            praktijkuitleg: 'Stel regels op voor thuiswerken en mobiel werken: versleutelde laptops, geen gevoelige documenten in auto.',
            hoofdvraag: 'Zijn er regels voor bedrijfsmiddelen buiten kantoor?',
            beleidsuitgangspunt: 'Beveiliging geldt ook buiten kantoor',
            doel: 'Verlies en diefstal voorkomen.',
            criticality: 'medium',
            customizable: true
        },
        {
            id: '7.11.01',
            titel: 'Nutsvoorzieningen',
            themaId: 'fysieke-beveiliging',
            categorie: 'Fysiek',
            description: 'Informatieverwerkende faciliteiten zijn beschermd tegen storingen in nutsvoorzieningen.',
            bioOriginalText: 'Faciliteiten behoren te worden beschermd tegen stroomuitval en andere verstoringen.',
            praktijkuitleg: 'Voorzie kritieke systemen van UPS en generator voor stroomuitval.',
            hoofdvraag: 'Zijn kritieke systemen beschermd tegen stroomuitval?',
            beleidsuitgangspunt: 'Beschikbaarheid borgen via redundantie',
            doel: 'Onderbreking van bedrijfsvoering voorkomen.',
            criticality: 'medium',
            customizable: true
        },

        // NIEUWE CONTROLS - Thema 8: Technologisch
        {
            id: '8.03.01',
            titel: 'Beperking toegang - Isolatie',
            themaId: 'toegangsbeveiliging',
            categorie: 'Technologisch',
            description: 'Maatregelen voor fysiek/logisch isoleren van informatie met specifiek belang.',
            bioOriginalText: 'De toegang tot informatie behoort te worden beperkt overeenkomstig het beleid.',
            praktijkuitleg: 'Isoleer gevoelige informatie fysiek (aparte servers) of logisch (netwerksegmentatie).',
            hoofdvraag: 'Is gevoelige informatie geïsoleerd?',
            beleidsuitgangspunt: 'Isolatie beperkt blootstelling',
            doel: 'Onbevoegde toegang voorkomen.',
            criticality: 'high',
            customizable: true
        },
        {
            id: '8.03.02',
            titel: 'Beperking toegang - Need to know',
            themaId: 'toegangsbeveiliging',
            categorie: 'Technologisch',
            description: 'Gebruikers kunnen alleen informatie inzien die nodig is voor hun taak.',
            bioOriginalText: 'De toegang tot informatie behoort te worden beperkt.',
            praktijkuitleg: 'Implementeer need-to-know principe: geef alleen toegang tot wat echt nodig is voor de functie.',
            hoofdvraag: 'Is toegang beperkt tot need-to-know?',
            beleidsuitgangspunt: 'Minimale toegang verkleint risico',
            doel: 'Onbevoegde toegang voorkomen.',
            criticality: 'high',
            customizable: true
        },
        {
            id: '8.08.04',
            titel: 'Beheer kwetsbaarheden - Jaarlijkse controle',
            themaId: 'operationele-beveiliging',
            categorie: 'Technologisch',
            description: 'Informatiesystemen worden jaarlijks gecontroleerd op kwetsbaarheden.',
            bioOriginalText: 'Er behoort informatie te worden verkregen over technische kwetsbaarheden.',
            praktijkuitleg: 'Voer jaarlijks pentests of vulnerability scans uit. Voor internetfacing systemen: continue testen.',
            hoofdvraag: 'Worden systemen jaarlijks op kwetsbaarheden getest?',
            beleidsuitgangspunt: 'Proactief zoeken naar zwakheden',
            doel: 'Misbruik van kwetsbaarheden voorkomen.',
            criticality: 'high',
            customizable: true
        },
        {
            id: '8.08.05',
            titel: 'Beheer kwetsbaarheden - Penetratietests',
            themaId: 'operationele-beveiliging',
            categorie: 'Technologisch',
            description: 'Internetfacing systemen hebben verplichte pentest bij elke release.',
            bioOriginalText: 'Er behoort informatie te worden verkregen over technische kwetsbaarheden.',
            praktijkuitleg: 'Laat alle internetfacing systemen testen voor productie en fix kritieke bevindingen eerst.',
            hoofdvraag: 'Worden internetfacing systemen getest voor release?',
            beleidsuitgangspunt: 'Test voor productie gaat',
            doel: 'Misbruik van kwetsbaarheden voorkomen.',
            criticality: 'high',
            customizable: true
        },
        {
            id: '8.11.01',
            titel: 'Maskeren van gegevens',
            themaId: 'operationele-beveiliging',
            categorie: 'Technologisch',
            description: 'Gegevens worden gemaskeerd volgens beleid en wetgeving.',
            bioOriginalText: 'Gegevens behoren te worden gemaskeerd overeenkomstig het beleid.',
            praktijkuitleg: 'Gebruik data masking in test/ontwikkelomgevingen zodat productiedata niet zichtbaar is.',
            hoofdvraag: 'Worden gevoelige data gemaskeerd in niet-productie omgevingen?',
            beleidsuitgangspunt: 'Data minimalisatie in niet-productie',
            doel: 'Openbaarmaking van gevoelige informatie beperken.',
            criticality: 'medium',
            customizable: true
        },
        {
            id: '8.13.02',
            titel: 'Back-up van informatie - RTO/RPO',
            themaId: 'operationele-beveiliging',
            categorie: 'Technologisch',
            description: 'Op basis van risicoanalyse is maximaal dataverlies en hersteltijd bepaald.',
            bioOriginalText: 'Back-ups behoren te worden bewaard en regelmatig te worden getest.',
            praktijkuitleg: 'Bepaal per systeem: hoeveel dataverlies is acceptabel (RPO) en hoe snel moet herstel (RTO).',
            hoofdvraag: 'Zijn RTO/RPO voor kritieke systemen vastgesteld?',
            beleidsuitgangspunt: 'Herstel mogelijk maken na verlies',
            doel: 'Herstel mogelijk maken na verlies van gegevens.',
            criticality: 'high',
            customizable: true
        },
        {
            id: '8.26.01',
            titel: 'Toepassingsbeveiligingseisen',
            themaId: 'systeemontwikkeling',
            categorie: 'Technologisch',
            description: 'Beveiligingseisen worden geïdentificeerd bij ontwikkelen of aanschaffen van applicaties.',
            bioOriginalText: 'Er behoren eisen aan informatiebeveiliging te worden geïdentificeerd bij ontwikkelen van toepassingen.',
            praktijkuitleg: 'Stel bij elk nieuw systeem eerst beveiligingseisen vast voordat ontwikkeling/aanschaf begint.',
            hoofdvraag: 'Worden beveiligingseisen vooraf vastgesteld?',
            beleidsuitgangspunt: 'Security by design',
            doel: 'Garanderen dat beveiligingseisen zijn geïdentificeerd.',
            criticality: 'high',
            customizable: true
        },
        {
            id: '8.29.01',
            titel: 'Testen van beveiliging tijdens ontwikkeling',
            themaId: 'systeemontwikkeling',
            categorie: 'Technologisch',
            description: 'Processen voor beveiligingstesten zijn gedefinieerd en geïmplementeerd.',
            bioOriginalText: 'Processen voor het testen van beveiliging behoren te worden gedefinieerd.',
            praktijkuitleg: 'Gebruik gestructureerde testmethodieken (bij voorkeur geautomatiseerd) en leg resultaten vast.',
            hoofdvraag: 'Worden beveiligingstesten geautomatiseerd uitgevoerd?',
            beleidsuitgangspunt: 'Valideren van beveiligingseisen',
            doel: 'Valideren dat aan beveiligingseisen wordt voldaan.',
            criticality: 'high',
            customizable: true
        },
        {
            id: '8.30.01',
            titel: 'Uitbestede systeemontwikkeling',
            themaId: 'systeemontwikkeling',
            categorie: 'Technologisch',
            description: 'Organisatie stuurt en beoordeelt uitbestede systeemontwikkeling.',
            bioOriginalText: 'De organisatie behoort activiteiten in verband met uitbestede ontwikkeling te sturen.',
            praktijkuitleg: 'Pas alle interne ontwikkeleisen ook toe op externe ontwikkelaars, inclusief uitbestedingsmaatregelen.',
            hoofdvraag: 'Worden beveiligingseisen doorgelegd aan externe ontwikkelaars?',
            beleidsuitgangspunt: 'Uitbesteding verandert verantwoordelijkheid niet',
            doel: 'Garanderen dat beveiligingsmaatregelen worden geïmplementeerd.',
            criticality: 'medium',
            customizable: true
        },
        {
            id: '8.32.01',
            titel: 'Wijzigingsbeheer - Procedure',
            themaId: 'systeemontwikkeling',
            categorie: 'Technologisch',
            description: 'Wijzigingen zijn onderworpen aan procedures voor wijzigingsbeheer.',
            bioOriginalText: 'Wijzigingen behoren onderworpen te zijn aan procedures voor wijzigingsbeheer.',
            praktijkuitleg: 'Procedure moet bevatten: administratie, risicoanalyse met rollback plan, goedkeuringsprocedure.',
            hoofdvraag: 'Is er een formele change management procedure?',
            beleidsuitgangspunt: 'Informatiebeveiliging behouden tijdens wijzigingen',
            doel: 'Beveiliging behouden tijdens uitvoeren van wijzigingen.',
            criticality: 'high',
            customizable: true
        },
        {
            id: '8.32.02',
            titel: 'Wijzigingsbeheer - Raamwerk',
            themaId: 'systeemontwikkeling',
            categorie: 'Technologisch',
            description: 'Wijzigingsbeheer vindt plaats op basis van algemeen geaccepteerd beheerraamwerk.',
            bioOriginalText: 'Wijzigingen behoren onderworpen te zijn aan procedures voor wijzigingsbeheer.',
            praktijkuitleg: 'Gebruik een erkend framework zoals ITIL voor change management.',
            hoofdvraag: 'Wordt een geaccepteerd raamwerk gebruikt voor wijzigingsbeheer?',
            beleidsuitgangspunt: 'Best practices volgen',
            doel: 'Beveiliging behouden tijdens wijzigingen.',
            criticality: 'medium',
            customizable: true
        },
        {
            id: '8.33.01',
            titel: 'Testgegevens',
            themaId: 'systeemontwikkeling',
            categorie: 'Technologisch',
            description: 'Testgegevens worden op passende wijze geselecteerd, beschermd en beheerd.',
            bioOriginalText: 'Testgegevens behoren op passende wijze te worden geselecteerd, beschermd en beheerd.',
            praktijkuitleg: 'Gebruik geen productiedata in test zonder anonimisering. Bij gebruik: zelfde beveiligingsniveau.',
            hoofdvraag: 'Worden testgegevens adequaat beschermd?',
            beleidsuitgangspunt: 'Testdata verdient zelfde bescherming',
            doel: 'Relevantie van testen en bescherming van operationele data waarborgen.',
            criticality: 'medium',
            customizable: true
        },

        // Bestaande controls uit origineel bestand (behouden)
        {
            id: '6.01.01',
            titel: 'Screeningsbeleid',
            themaId: 'personele-beveiliging',
            description: 'Elke organisatie heeft een vastgesteld screeningsbeleid.',
            bioOriginalText: 'De organisatie heeft een beleid voor screening van personeel voorafgaand aan aanstelling.',
            praktijkuitleg: 'Stel een beleid op dat beschrijft hoe nieuwe medewerkers worden gescreend voordat ze toegang krijgen.',
            hoofdvraag: 'Is er een beleid voor het screenen van nieuwe medewerkers?',
            beleidsuitgangspunt: 'Screening vermindert het risico van onbetrouwbaar personeel',
            criticality: 'medium',
            customizable: true
        },
        {
            id: '5.17.01',
            titel: 'Multi-factorauthenticatie (MFA)',
            themaId: 'toegangsbeveiliging',
            description: 'MFA wordt toegepast voor primair aanloggen, internet-bereikbare voorzieningen en beheeraccounts.',
            bioOriginalText: 'Multi-factorauthenticatie wordt toegepast voor toegang tot gevoelige systemen.',
            praktijkuitleg: 'Implementeer MFA voor alle belangrijke systemen: email, werkplek, admin-accounts en internet-toegankelijke diensten.',
            hoofdvraag: 'Is MFA geïmplementeerd voor kritieke systemen?',
            beleidsuitgangspunt: 'Een wachtwoord alleen is niet voldoende beveiliging',
            criticality: 'high',
            customizable: true
        },
        {
            id: '8.07.03',
            titel: 'Antimalware-software',
            themaId: 'operationele-beveiliging',
            description: 'Antimalware-software is actueel en wordt ondersteund door periodieke updates.',
            bioOriginalText: 'Antimalware-software wordt geïnstalleerd en regelmatig bijgewerkt.',
            praktijkuitleg: 'Installeer en onderhoud antivirus software op alle systemen met automatische updates.',
            hoofdvraag: 'Is er actuele antimalware-software geïnstalleerd?',
            beleidsuitgangspunt: 'Preventie is beter dan herstel bij malware',
            criticality: 'high',
            customizable: true
        },
        {
            id: '8.13.01',
            titel: 'Back-upbeleid',
            themaId: 'operationele-beveiliging',
            description: 'Er is een back-upbeleid waarin eisen voor bewaren en beschermen zijn gedefinieerd.',
            bioOriginalText: 'De organisatie heeft een back-upbeleid.',
            praktijkuitleg: 'Maak een formeel back-upbeleid en test regelmatig of restore werkt.',
            hoofdvraag: 'Is er een formeel back-upbeleid?',
            beleidsuitgangspunt: 'Back-ups zijn essentieel voor bedrijfscontinuïteit',
            criticality: 'high',
            customizable: true
        },
        {
            id: '8.24.01',
            titel: 'Inhoud cryptografiebeleid',
            themaId: 'cryptografie',
            description: 'Cryptografiebeleid beschrijft wanneer cryptografie wordt ingezet en wie verantwoordelijk is.',
            bioOriginalText: 'Het cryptografiebeleid beschrijft wanneer en hoe cryptografie wordt toegepast.',
            praktijkuitleg: 'Stel beleid op voor gebruik van versleuteling en beschrijf implementatie en beheer.',
            hoofdvraag: 'Is er een cryptografiebeleid?',
            beleidsuitgangspunt: 'Versleuteling beschermt data bij diefstal',
            criticality: 'medium',
            customizable: true
        },

        // AI Governance (behouden)
        {
            id: 'AI_GOV_1.1',
            titel: 'Beleid voor Acceptabel Gebruik van AI',
            themaId: 'ai-governance',
            description: 'Er is een formeel beleid voor gebruik van AI door medewerkers.',
            bioOriginalText: 'De organisatie heeft een beleid voor verantwoord gebruik van kunstmatige intelligentie.',
            praktijkuitleg: 'Stel AI-gebruiksbeleid op dat beschrijft wanneer en hoe medewerkers AI-tools mogen gebruiken.',
            hoofdvraag: 'Is er een beleid voor het gebruik van AI-tools?',
            beleidsuitgangspunt: 'AI biedt kansen maar vereist bewuste sturing',
            criticality: 'medium',
            customizable: true
        },
        {
            id: 'AI_GOV_1.2',
            titel: 'Register van AI-toepassingen',
            themaId: 'ai-governance',
            description: 'De organisatie onderhoudt een register van alle AI-toepassingen.',
            bioOriginalText: 'Er wordt een overzicht bijgehouden van alle AI-systemen binnen de organisatie.',
            praktijkuitleg: 'Maak een lijst van alle AI-tools en houd bij wie het gebruikt en voor welk doel.',
            hoofdvraag: 'Is er een actueel overzicht van alle AI-toepassingen?',
            beleidsuitgangspunt: 'Je kunt alleen beheersen wat je kent',
            criticality: 'medium',
            customizable: true
        }
    ],

    MAPPINGS: {
        // Mappings naar andere standaarden kunnen hier worden toegevoegd
    }
};

// Export voor gebruik in IBH en IBAT
const WETGEVING_CONTROLS = CENTRAAL_KADER.CONTROLS;